"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.runScannerLabEngineEvaluations = exports.playbackCandlesToEngine = exports.engineSnapshotToDerivedIndicators = exports.deriveIndicators = exports.MIN_ENGINE_BARS = exports.DEFAULT_DETECTOR_OPTIONS = void 0;
var scannerLabEngineAdapter_1 = require("@/lib/scannerLabEngineAdapter");
Object.defineProperty(exports, "DEFAULT_DETECTOR_OPTIONS", { enumerable: true, get: function () { return scannerLabEngineAdapter_1.DEFAULT_DETECTOR_OPTIONS; } });
Object.defineProperty(exports, "MIN_ENGINE_BARS", { enumerable: true, get: function () { return scannerLabEngineAdapter_1.MIN_ENGINE_BARS; } });
Object.defineProperty(exports, "deriveIndicators", { enumerable: true, get: function () { return scannerLabEngineAdapter_1.deriveIndicators; } });
Object.defineProperty(exports, "engineSnapshotToDerivedIndicators", { enumerable: true, get: function () { return scannerLabEngineAdapter_1.engineSnapshotToDerivedIndicators; } });
Object.defineProperty(exports, "playbackCandlesToEngine", { enumerable: true, get: function () { return scannerLabEngineAdapter_1.playbackCandlesToEngine; } });
Object.defineProperty(exports, "runScannerLabEngineEvaluations", { enumerable: true, get: function () { return scannerLabEngineAdapter_1.runScannerLabEngineEvaluations; } });
