name: Dependabot Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Enable auto-merge for safe updates
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash

      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
